# Generated by Django 5.2.2 on 2025-06-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='USN-ID', max_length=20, unique=True),
        ),
    ]
